### ISSUE TITLE
Consider pulling in enhancements from original csrp project

### ISSUE THREAD

**Issue by cocagne** [est31/csrp-gmp#4]
Just came across csrp-gmp. Nice work! My original implementation of csrp was originally built on top of gmp but I switched to openssl due to the assumption (which may have been wrong) that it was more widely known and readily available than gmp. I'd like to have supported both via conditional compilation but I was dealing with a newborn at the time and the energy needed to wrangle the c  preprocessor into submission was severely lacking (and it's still lacking 5 years later ;-). 

Anyway, there have been several security fixes and enhancements made in recent years that you may want to consider migrating over to csrp-gmp, particularly so in the rfc5054_compat branch, which seems to be the emerging standard for inter-implementation compatibility (RFC5054, that is). Aside from compatibility & security enhancements, the project has been relatively quiet for several years now so an inspection of the commit history is probably all the more that would be required to determine if the changes made are worth bringing over.

Cheers,

Tom

**Comment by est31** [comment]
Thanks for your feedback!

The choice to port over to gmp was done due to the size of openssl (its made for many other tasks than just big int manipulation), and at the time (first half of 2015) it was riddled with bugs, each week you'd hear of new major bugs in openssl. The main usecase for csrp-gmp is [minetest](https://github.com/minetest/minetest), where one of the goals was to make compiling on windows as easy as possible. Requiring people to fetch and build and integrate yet another library would be too much hassle. gmp offers mini-gmp which was bundled with the minetest source code. People still can use official gmp if they want to.

During the porting work, I've strived to get RFC5054 compatibility for the library, so it should be already switched on the master branch. Also, I've done many security fixes and const-ness improvements (If I remember correctly, there were some constness errors in the library...).

As the fork happened in 2015, most changes would already be inside csrp-gmp.

The only recent change I haven't seen seems to be https://github.com/cocagne/csrp/commit/7a1484e4b1c64b9e542612679aa67cbfe085a292 but unless I'm mistaken it seems to be already done in my codebase.

Obviously, as the project is open source, the license allows you to bring over any changes into your project that you want.
